label.data.inicial = Data inicial
label.data.final = Data final
label.gerar = Gerar
label.exportar.excel = Exportar
label.relatorio.semPesquisa = Informe o período e clique em Gerar para ver os resultados.