label.titulo.pagina = Titulo da Pagina
label.novo = Novo
label.excluir = Excluir
label.editar = Editar
label.acao = Ação
label.id = Id
label.nome = Nome
label.buscar.por = Buscar por
label.escolha = Escolha...
label.pesquisar = Pesquisar
label.sim = Sim
label.nao = Não
label.modal.titulo = Confirmar exclusão?
label.modal.corpo = Deseja excluir?

label.menu.funcionarios = Funcionários
label.menu.compromissos = Compromissos
label.menu.agenda = Agenda
label.menu.relatorio = Relatório

label.periodo = Período
label.periodo.MANHA = Manhã
label.periodo.TARDE = Tarde
label.periodo.AMBOS = Ambos

label.funcionario = Funcionário
label.agenda = Agenda
label.data = Data
label.horario = Horário

label.data.inicial = Data inicial
label.data.final = Data final
label.gerar = Gerar
label.exportar.excel = Exportar

label.erro.titulo = Não foi possível concluir a operação
label.erro.voltar = Voltar
label.erroTecnico.titulo = Erro inesperado
label.erroTecnico.mensagem = Ocorreu um problema inesperado. Tente novamente mais tarde ou entre em contato com o suporte.





