java.time.LocalDate=br.com.soc.sistema.util.LocalDateConverter
java.time.LocalTime=br.com.soc.sistema.util.LocalTimeConverter

br.com.soc.sistema.infra.OpcoesComboBuscarAgenda=br.com.soc.sistema.util.OpcoesComboBuscarAgendaConverter
br.com.soc.sistema.infra.OpcoesComboBuscar=br.com.soc.sistema.util.OpcoesComboBuscarConverter